# Generated by Django 6.0.1 on 2026-01-11 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100, unique=True, verbose_name='プレイヤーID')),
                ('total_games', models.IntegerField(default=0, verbose_name='総ゲーム数')),
                ('cleared_games', models.IntegerField(default=0, verbose_name='クリア数')),
                ('total_attempts', models.IntegerField(default=0, verbose_name='総試行回数')),
                ('best_attempts', models.IntegerField(blank=True, null=True, verbose_name='最少試行回数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'プレイヤー戦績',
                'verbose_name_plural': 'プレイヤー戦績',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_number', models.IntegerField(unique=True, verbose_name='図鑑番号')),
                ('name_ja', models.CharField(max_length=100, verbose_name='日本語名')),
                ('name_en', models.CharField(max_length=100, verbose_name='英語名')),
                ('type1', models.CharField(max_length=50, verbose_name='タイプ1')),
                ('type2', models.CharField(blank=True, max_length=50, null=True, verbose_name='タイプ2')),
                ('height', models.FloatField(verbose_name='高さ(m)')),
                ('weight', models.FloatField(verbose_name='重さ(kg)')),
                ('generation', models.IntegerField(verbose_name='世代')),
                ('evolution_count', models.IntegerField(default=0, verbose_name='進化回数')),
            ],
            options={
                'verbose_name': 'ポケモン',
                'verbose_name_plural': 'ポケモン',
                'ordering': ['pokedex_number'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('player_id', models.CharField(max_length=100, verbose_name='プレイヤーID')),
                ('attempts', models.IntegerField(default=0, verbose_name='試行回数')),
                ('status', models.CharField(choices=[('playing', 'プレイ中'), ('cleared', 'クリア'), ('failed', '失敗')], default='playing', max_length=20, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('target_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.pokemon', verbose_name='お題ポケモン')),
            ],
            options={
                'verbose_name': 'ゲームセッション',
                'verbose_name_plural': 'ゲームセッション',
                'ordering': ['-created_at'],
            },
        ),
    ]
