# Generated by Django 6.0.1 on 2026-01-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='max_attempts',
            field=models.IntegerField(default=8, verbose_name='最大試行回数'),
        ),
    ]
